export { default as Navbar } from './NavBar'
export { default as HomePage } from './HomePage'
export { default as News } from './News'
export { default as CryptoCurrencies } from './CryptoCurrencies'
export { default as CryptoDetails } from './CryptoDetails'
export { default as Exchanges } from './Exchanges'
